### ISSUE TITLE
EPIC: GraphiQL UI

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-smart-cache#41]
This issue is an outline of the work to be done to get WPGraphQL Persisted Queries working with GraphiQL

## Initial JS Scaffolding

- [ ] Initial JavaScript scaffolding using wp-scripts, etc
- [ ] Automate builds on release?

## Hook into GraphiQL

- [ ] Register a new "Screen" to show in GraphiQL
- [ ] Render new Document Editor Screen in GraphiQL

## Document Editor Screen

The Document Editor is comprised of 3 main components (Document Finder, Active Document Tabs, File Menu)

These will all need to share some state and functionality with each other. For example, the Document Finder and File Menu will both need to be able to open documents in a new tab, etc. The Document Tabs and File Menu will need to be able to save/close documents from the tabs, etc.

### Document Finder
- [ ] List of existing documents
   - [ ] Each document should show attributes such as: Document Title, TTL, allow/deny state, publish (active) state, etc
   - [ ] Each Document should have actions (edit, trash, delete), etc

### Document Tabs
- [ ] Open new tab (unsaved document)
- [ ] Open multiple documents in a tabbed interface
- [ ] Save a document
- [ ] Delete a document
- [ ] Close a document
- [ ] Edit a document
   - [ ] Change document (query string)
   - [ ] Change TTL
   - [ ] Change Allow/Deny state

**Comment by jasonbahl** [comment]
Closing this issue as individual features are now tracked within  the "Memo: Smart Cache UI in IDE" workstream in the Github Project board.
